### ISSUE TITLE
Certificate errors when starting with INSECURE=true

### ISSUE THREAD

**Issue by instantdreams** [DRuggeri/netgear_exporter#11]
When starting a container using docker-compose the logs indicate an issue with an x509 certificate despite the URL being a LAN address and INSECURE being set to "true".

**docker-compose.yml**:
```
version: "3"
services:
  netgear_exporter:
    image: druggeri/netgear_exporter:latest
    container_name: netgear_exporter
    environment:
      - URL=${URL}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - NETGEAR_EXPORTER_PASSWORD=${PASSWORD}
      - WEB_AUTH_USERNAME=${WEB_AUTH_USERNAME}
      - WEB_AUTH_PASSWORD=${WEB_AUTH_PASSWORD}
      - INSECURE=true
      - CLIENTDEBUG
      - METRICS_NAMESPACE=netgear
      - TIMEOUT=2
    ports:
      - 9192:9192
    restart: unless-stopped
```

**.env.example**:
```
# Container specifics
URL=[url]
USERNAME=[username]
PASSWORD=[password]
WEB_AUTH_USERNAME=[username]
WEB_AUTH_PASSWORD=[password]
NETGEAR_EXPORTER_PASSWORD=[password]
```

**log file tail**:
```
$ docker-compose --file /srv/netgear_exporter/docker-compose.yml logs
Attaching to netgear_exporter
netgear_exporter    | time="2022-10-18T16:34:19Z" level=info msg="Starting node_exporter 2.0.3" source="netgear_exporter.go:180"
netgear_exporter    | time="2022-10-18T16:34:19Z" level=info msg="Listening on :9192" source="netgear_exporter.go:230"
netgear_exporter    | time="2022-10-18T16:34:21Z" level=error msg="Error while collecting system info: Post \"https://www.routerlogin.com/soap/server_sa/\": x509: certificate is not valid for any names, but wanted to match www.routerlogin.com" source="system_info_collector.go:110"
netgear_exporter    | time="2022-10-18T16:34:21Z" level=error msg="Error while collecting client statistics: Post \"https://www.routerlogin.com/soap/server_sa/\": x509: certificate is not valid for any names, but wanted to match www.routerlogin.com" source="clients_collector.go:122"
netgear_exporter    | time="2022-10-18T16:34:21Z" level=error msg="Error while collecting traffic statistics: Post \"https://www.routerlogin.com/soap/server_sa/\": x509: certificate is not valid for any names, but wanted to match www.routerlogin.com" source="traffic_collector.go:126"
```

The container seems to be trying to connect to www.routerlogin.com rather than my LAN address. Here is a sanitised version of the loaded configuration:
```
$ docker-compose --file /srv/netgear_exporter/docker-compose.yml config
services:
  netgear_exporter:
    container_name: netgear_exporter
    environment:
      CLIENTDEBUG: null
      INSECURE: "true"
      METRICS_NAMESPACE: netgear
      NETGEAR_EXPORTER_PASSWORD: [password]
      PASSWORD: [password]
      TIMEOUT: '2'
      URL: http://192.168.1.1/
      USERNAME: [username]
      WEB_AUTH_PASSWORD: [username]
      WEB_AUTH_USERNAME: [username]
    image: druggeri/netgear_exporter:latest
    ports:
    - published: 9192
      target: 9192
    restart: unless-stopped
version: '3'
```

Any ideas what is happening?
