### ISSUE TITLE
Inconsistent Environment variables around password fields

### ISSUE THREAD

**Issue by instantdreams** [DRuggeri/netgear_exporter#12]
When using docker-compose the password fields are inconsistent. Using the following compose file results in an error:

```
version: "3"
services:
  netgear_exporter:
    image: druggeri/netgear_exporter:latest
    container_name: netgear_exporter
    environment:
      - URL=${URL}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - WEB_AUTH_USERNAME=${WEB_AUTH_USERNAME}
      - WEB_AUTH_PASSWORD=${WEB_AUTH_PASSWORD}
      - INSECURE=true
      - CLIENTDEBUG
      - METRICS_NAMESPACE=netgear
      - TIMEOUT=2
    ports:
      - 9192:9192
    restart: unless-stopped
```

The error is around the environment variable:
```
$ docker-compose --file /srv/netgear_exporter/docker-compose.yml logs
Attaching to netgear_exporter
netgear_exporter    | ERROR: The password for the SOAP API must be set in the environment variable NETGEAR_EXPORTER_PASSWORD
netgear_exporter    | ERROR: The password for the SOAP API must be set in the environment variable NETGEAR_EXPORTER_PASSWORD
netgear_exporter    | ERROR: The password for the SOAP API must be set in the environment variable NETGEAR_EXPORTER_PASSWORD
netgear_exporter    | ERROR: The password for the SOAP API must be set in the environment variable NETGEAR_EXPORTER_PASSWORD
netgear_exporter    | ERROR: The password for the SOAP API must be set in the environment variable NETGEAR_EXPORTER_PASSWORD
```

Are all environment variables expected to be prefixed with NETGEAR_EXPORTER_ ?

**Comment by instantdreams** [comment]
I adjusted the docker-compose.yml as follows:
```
version: "3"
services:
  netgear_exporter:
    image: druggeri/netgear_exporter:latest
    container_name: netgear_exporter
    environment:
      - NETGEAR_EXPORTER_URL=${URL}
      - NETGEAR_EXPORTER_USERNAME=${USERNAME}
      - NETGEAR_EXPORTER_PASSWORD=${PASSWORD}
      - NETGEAR_EXPORTER_INSECURE=true
      - NETGEAR_EXPORTER_TIMEOUT=2
      - NETGEAR_EXPORTER_CLIENT_DEBUG=true
      - NETGEAR_EXPORTER_FILTER_COLLECTORS=Client,SystemInfo,Traffic
      - NETGEAR_EXPORTER_METRICS_NAMESPACE=id_router
    ports:
      - 9192:9192
    restart: unless-stopped
```
Now everything appears to be working.
```
$ docker-compose --file /srv/netgear_exporter/docker-compose.yml logs
Attaching to netgear_exporter
netgear_exporter    | time="2022-10-18T16:55:15Z" level=info msg="Starting node_exporter 2.0.3" source="netgear_exporter.go:180"
netgear_exporter    | 2022/10/18 16:55:15 netgear_client.go: Constructing debug client
netgear_exporter    | time="2022-10-18T16:55:15Z" level=info msg="Listening on :9192" source="netgear_exporter.go:230"
```

@DRuggeri Once you confirm this we can close the issue.
